language: go
go:
- 1.9
env:
  matrix:
  - DEP_VERSION="0.3.2"
  global:
  - secure: 00viW0J13FMTH20WofuvnavlpEKJp2NqsI7Q2+W45Jfymlrz2w9g6QLee4Z56BbY5dNzqHZV0K7+bfVZqsRtLnW6p9P2HlJ8yLLttC0oKz+AZ/B1mLznOEbKXa56TX6va5vQySdkCNDbZHZtBZ1bFeLkR192YW0gWLrXvkMC1tzjBhpem42gi+gpWy/APFNqDAogKitU4XzuLGgB3+9A93z+L3OPD2DeRlKMarJM5dC/iAXeC4tI53yktvyyJu+5BDEvUZkU4X36ZyvJL19SNbx5lCuXNkLtEm2mkqrUfkz2g3pDHhgwZqU3kR5slpZDAxqMo3e/G7zuEozQjxpIBJ5B8/2dqHrjkLFD732nynGMU4Nn+VN7P29X0IAbn8maxL/QYbqhgDIexzQsea85EGodFJNcgFZFzgDWs3SsR0vG5w6hOzYKVRt4QEDL1XphnWnJ8negUiUX/ISq5JNJGwLZa+w160VPmuOWsvYdeKk9yc1RdwBuiMaq3Dw2cOThd5ySzvPuhPc+Tq9j7GnFUuRaoZ5q1/63dXyrbYenOUpj3FflOdHDu6njMFbi+WhSY9U3vrzJzUQutsN2YxW4PDu9kNECWsZ4X2mYOkTuLHNQ6/oAgL7oxWntforgv7EIviq80harzZTJkLxKl9l0ei7kPrd3wgVGKPOaGmsK3L4=
  - secure: pbpc0mSUtM0CnTa/uekgQrid9t43uEygfOLllyy1ysebEdPVxJicH3iuFFzaDzxb/j9Gt8MSkHKKaL3ADzpOYWj2LuWdyMEx658H/sOCL4chV36ggUAtSKfqkpg9wG6ypmxsYZnjK6rLcs/+RE1slssv3RSyrhHbXgURoYVRbKJ7rypUugFDL7jcX/Zk37NNw6CEVHimNaDMoQQDo6yM/LsVmemuaXx06eJt+ij1r+iG6DiGNfNOCbUi2PS/YDkAAgcE0qMKfsQ84bj8Nqec+bwc3YP0HAnJXGkL83F1s3NuLHEUialx4eMXJQexLI+usy8fvU/5ui715xZm0wh/Py7BxDgv9xw6gxLi5+9KlVdqIgrlU56/pRLlfxj+Y0AqoujKL1ADhaU7P5YSN8zfAVx/Tdm2lh7YPQNRsvpJt84/9Ga5cVmBuSv0n+yPU9ZDlLrf7XfYgeu3Cs1o59DNrVfb4CNY6uoZZsSmmX/q+dl0U7ja4zxcHM9MPExO3xpnvHz/98Iey9LRdyzvWTmwLzg2G10CRsxBujQN69RPQ9drnRorR4jsUd9TtVmA09W4uGkT2i8TILC0MVmFVrkCB/28GmuamKnkxSzuZj1utTZrRNaC+wOOmGVus/s4nW0Q7WCEdGTjDXkwt/fZJxoBzDEyOj0V45HekuhSyEl6Q7Y=
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
install:
- dep ensure
script:
- go vet
- goveralls -repotoken ${repo_token}
