version: '3'
services:
  app:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - "mongo"
      - "redis"
  redis:
    image: "redis:alpine"
  mongo:
    ports:
    - "27017:27017"
    image: "mongo:latest"
    

